export const SET_IMAGE_DRAW_SETTINGS = 'SET_IMAGE_DRAW_SETTINGS';
export const SET_IMAGE = 'SET_IMAGE';
export const SET_DRAW_ITEM = 'SET_DRAW_ITEM';
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const DELETE_DRAW_ITEMS = 'DELETE_DRAW_ITEMS';
